name: dio_brotli_transformer
description: Brotli support for Dio http client
version: 2.0.0
homepage: https://github.com/vycius/dio_brotli_transformer

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  brotli: ^0.6.0
  dio: ">=5.0.0 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
