name: dio_brotli_transformer
description: Brotli support for Dio http client
version: 1.0.1
homepage: https://github.com/vycius/dio_brotli_transformer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  brotli: ^0.5.0
  dio: ">=4.0.0 <5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0
