name: dio_brotli_transformer
description: Brotli support for Dio http client
version: 0.1.0
author: Karolis Vycius <k.vycius@gmail.com>
homepage:

environment:
  sdk: ">2.4.0 <3.0.0"

dependencies:
  dio: ">=3.0.0 <4.0.0"
  brotli: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
